// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using oed_authz.Infrastructure.Database;

#nullable disable

namespace oed_authz.Infrastructure.Database.Migrations
{
    [DbContext(typeof(OedAuthzDbContext))]
    [Migration("20250512094631_Add_justification_column")]
    partial class Add_justification_column
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("oedauthz")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "oedauthz", "roleassignments_action", new[] { "GRANT", "REVOKE" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("oed_authz.Infrastructure.Database.Model.RoleAssignmentLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("oedauthz.roleassignments_action")
                        .HasColumnName("action");

                    b.Property<string>("EstateSsn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("estateSsn")
                        .IsFixedLength();

                    b.Property<string>("HeirSsn")
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("heirSsn")
                        .IsFixedLength();

                    b.Property<string>("Justification")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("justification");

                    b.Property<string>("RecipientSsn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("recipientSsn")
                        .IsFixedLength();

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("roleCode");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("roleassignments_log_pkey");

                    b.HasIndex(new[] { "EstateSsn" }, "idx_roleassignments_log_estatessn");

                    b.HasIndex(new[] { "RecipientSsn" }, "idx_roleassignments_log_recipientssn");

                    b.HasIndex(new[] { "Timestamp" }, "idx_roleassignments_log_timestamp");

                    b.ToTable("roleassignments_log", "oedauthz");
                });

            modelBuilder.Entity("oed_authz.Models.RoleAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("EstateSsn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("estateSsn")
                        .IsFixedLength();

                    b.Property<string>("HeirSsn")
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("heirSsn")
                        .IsFixedLength();

                    b.Property<string>("Justification")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("justification");

                    b.Property<string>("RecipientSsn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("recipientSsn")
                        .IsFixedLength();

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("roleCode");

                    b.HasKey("Id")
                        .HasName("roleassignments_pkey");

                    b.HasIndex(new[] { "EstateSsn", "RecipientSsn", "RoleCode", "HeirSsn" }, "constraint_roleassignment")
                        .IsUnique();

                    b.HasIndex(new[] { "Created" }, "idx_created");

                    b.HasIndex(new[] { "EstateSsn" }, "idx_estatessn");

                    b.HasIndex(new[] { "RecipientSsn" }, "idx_recipientSsn");

                    b.HasIndex(new[] { "RoleCode" }, "idx_roleCode");

                    b.HasIndex(new[] { "EstateSsn", "RecipientSsn", "RoleCode" }, "idx_unique_collective_roleassignments")
                        .IsUnique()
                        .HasFilter("(\"heirSsn\" IS NULL)");

                    b.ToTable("roleassignments", "oedauthz");
                });
#pragma warning restore 612, 618
        }
    }
}
